hasCJKLanguage = true
summaryLength = 300
baseURL = 'https://123weiweiwbh.github.io/zyyjx999/'
languageCode = 'en-us'
title = 'My New Hugo Site'
publishDir = "docs"
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

